steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Deploy to GCP
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      
logsBucket: 'gs://printwear-414416.appspot.com'
options:
  logging: GCS_ONLY