steps:
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'create-env']
    env:
      - 'MY_SECRET_KEY=${_MY_SECRET_KEY}'
      - 'MONGODB_URL=${_MONGODB_URL}'
      - 'TWILIO_ACCOUNT_SID=${_TWILIO_ACCOUNT_SID}'
      - 'TWILIO_AUTH_TOKEN=${_TWILIO_AUTH_TOKEN}'
      - 'CASH_MODE=${_CASH_MODE}'
      - 'CASH_APP_ID=${_CASH_APP_ID}'
      - 'CASH_SECRET_KEY=${_CASH_SECRET_KEY}'
      - 'CASH_TEST_APP_ID=${_CASH_TEST_APP_ID}'
      - 'CASH_TEST_SECRET_KEY=${_CASH_TEST_SECRET_KEY}'
      - 'ZOHO_CLIENT_ID=${_ZOHO_CLIENT_ID}'
      - 'ZOHO_CLIENT_SECRET=${_ZOHO_CLIENT_SECRET}'
      - 'ZOHO_ACCESS_TOKEN=${_ZOHO_ACCESS_TOKEN}'
      - 'ZOHO_REFRESH_TOKEN=${_ZOHO_REFRESH_TOKEN}'
      - 'ZOHO_API_URL=${_ZOHO_API_URL}'
      - 'WOOCOMMERCE_CONSUMER_KEY=${_WOOCOMMERCE_CONSUMER_KEY}'
      - 'WOOCOMMERCE_CONSUMER_SECRET=${_WOOCOMMERCE_CONSUMER_SECRET}'
      - 'CASHFREE_BASE_URL=${_CASHFREE_BASE_URL}'
      - 'CASHFREE_BASE_URL_TEST=${_CASHFREE_BASE_URL_TEST}'
      - 'WEBHOOK_URL=${_WEBHOOK_URL}'
      - 'SHIPROCKET_URL=${_SHIPROCKET_URL}'
      - 'SHIPROCKET_EMAIL=${_SHIPROCKET_EMAIL}'
      - 'SHIPROCKET_SECRET=${_SHIPROCKET_SECRET}'
      - 'SHIPROCKET_CHANNEL_ID=${_SHIPROCKET_CHANNEL_ID}'
      - 'WOO_PROD_CONSUMER_KEY=${_WOO_PROD_CONSUMER_KEY}'
      - 'WOO_PROD_CONSUMER_SECRET=${_WOO_PROD_CONSUMER_SECRET}'
      - 'JWT_SECRET=${_JWT_SECRET}'
      - 'CASHFREE_PAYOUT_TEST=${_CASHFREE_PAYOUT_TEST}'
      - 'CASHFREE_PAYOUT_PROD=${_CASHFREE_PAYOUT_PROD}'
      - 'CF_PAYOUT_CLIENT_TEST=${_CF_PAYOUT_CLIENT_TEST}'
      - 'CF_PAYOUT_SECRET_TEST=${_CF_PAYOUT_SECRET_TEST}'
      - 'CF_PAYOUT_CLIENT_PROD=${_CF_PAYOUT_CLIENT_PROD}'
      - 'CF_PAYOUT_SECRET_PROD=${_CF_PAYOUT_SECRET_PROD}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'
      
logsBucket: 'gs://printwear-414416.appspot.com'
options:
  logging: GCS_ONLY