steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Build Node.js app
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run']

  # Deploy to GCP
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'